name: Simple CI pipeline

on:
    push:
       branches: ["main"]
    pull_request:
       branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3

     - name: Run a simple command
       run: echo "Pipline run"

     - name: Step1
       run: echo "This is my step 1"

     - name: Step2
       run: echo "This is my step 2"

     - name: pipeline break
       run: echo "the pipeline is fixed"

    
        

  